name: GitHub Classroom Workflow
on: [push]
jobs:
      build:
        name: Autograding
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - name: Setup Python
            uses: actions/setup-python@v2
            with:
                python-version: 3.7
          - name: Install pytest
            run: |
                 pip3 install pytest
          - uses: education/autograding@v1
